### ISSUE TITLE
Job/configure-canal CrashLoopBackOff

### ISSUE THREAD

**Issue by kharisj** [tigera/canal#15]
They cannot start configure canal container in kubernetes's node as following

```
[root@master manifests]# kubectl get po --all-namespaces
NAMESPACE     NAME                                   READY     STATUS              RESTARTS   AGE
kube-system   calico-policy-controller-m74q6         1/1       Running             0          8m
kube-system   canal-node-b1k9b                       3/3       Running             0          8m
kube-system   canal-node-egi67                       3/3       Running             0          8m
kube-system   canal-node-hf2bp                       3/3       Running             0          8m
kube-system   configure-canal-ds7dp                  0/1       CrashLoopBackOff    6          8m
kube-system   etcd-master.local                      1/1       Running             0          2h
kube-system   kube-apiserver-master.local            1/1       Running             0          1h
kube-system   kube-controller-manager-master.local   1/1       Running             0          2h
kube-system   kube-discovery-982812725-rvrsi         1/1       Running             0          2h
kube-system   kube-dns-2247936740-fp4lh              0/3       ContainerCreating   0          29m
kube-system   kube-proxy-amd64-9w007                 1/1       Running             0          2h
kube-system   kube-proxy-amd64-j0cqs                 1/1       Running             0          2h
kube-system   kube-proxy-amd64-vppqb                 1/1       Running             0          2h
kube-system   kube-scheduler-master.local            1/1       Running             0          2h
```

and from docker container

```
[root@minion02 ~]# docker ps -a|grep etcd
18b0a5821c84        quay.io/coreos/etcd:v3.0.9                         "etcdctl set /coreos."   About a minute ago   Exited (4) About a minute ago                       k8s_configure-flannel.5cb8baa7_configure-canal-ds7dp_kube-system_f422e416-944e-11e6-af58-000c29d821b6_840b6cb5
[root@minion02 ~]# docker logs 18b0a5821c84
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
```

Config.yaml

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: canal-config 
  namespace: kube-system
data:
  etcd_endpoints: "http://192.168.10.137:2379"
  canal_iface: ""
  masquerade: "true"
  cni_network_config: |-
    {
        "name": "canal",
        "type": "flannel",
        "delegate": {
          "type": "calico",
          "etcd_endpoints": "__ETCD_ENDPOINTS__",
          "log_level": "info",
          "policy": {
              "type": "k8s",
              "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
              "k8s_api_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
              "kubeconfig": "/etc/cni/net.d/__KUBECONFIG_FILENAME__"
          }
        }
    }

```

**Comment by kharisj** [comment]
`[root@master manifests]# kubectl describe -n kube-system po configure-canal-ds7dp
Name:           configure-canal-ds7dp
Namespace:      kube-system
Node:           minion02.local/192.168.10.140
Start Time:     Mon, 17 Oct 2016 16:49:10 +0700
Labels:         controller-uid=f41aae19-944e-11e6-af58-000c29d821b6
                job-name=configure-canal
Status:         Running
IP:             192.168.10.140
Controllers:    Job/configure-canal
Containers:
  configure-flannel:
    Container ID:       docker://e45b4b8ad756b846ff3a9e7c919cc429a500698d3854324e242462dae5a4897d
    Image:              quay.io/coreos/etcd:v3.0.9
    Image ID:           docker://sha256:6146fc8fb233312fd2f279cbf6098568cfeb8fda15222ae514b37cba8c6617bf
    Port:
    Command:
      etcdctl
      set
      /coreos.com/network/config
      { "Network": "192.168.0.0/16", "Backend": {"Type": "vxlan"} }
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Error
      Exit Code:        4
      Started:          Mon, 17 Oct 2016 16:49:35 +0700
      Finished:         Mon, 17 Oct 2016 16:49:35 +0700
    Ready:              False
    Restart Count:      2
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-buxtr (ro)
    Environment Variables:
      ETCDCTL_PEERS:    <set to the key 'etcd_endpoints' of config map 'canal-config'>
Conditions:
  Type          Status
  Initialized   True
  Ready         False
  PodScheduled  True
Volumes:
  default-token-buxtr:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-buxtr
QoS Class:      BestEffort
Tolerations:    <none>`

**Comment by caseydavenport** [comment]
> error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused

Seems to indicate that it isn't picking up the correct `etcd_endpoints` (since your config seems to indicate `etcd_endpoints: "http://192.168.10.137:2379"` 

Interestingly, it does look like the pod is picking it up: `ETCDCTL_PEERS:    <set to the key 'etcd_endpoints' of config map 'canal-config'>`

I'm not sure what exactly, but something is going wrong in populating `ETCDCTL_PEERS`.  Can you verify that `env` inside that container shows the correct value for `ETCDCTL_PEERS`?

**Comment by kharisj** [comment]
I tried to bringing system up again but I think it's too late everything is changed. I give up and head to use kubeadm so it's not working again may be trouble than before. As my attached it's all Crash.
[canal.log.txt](https://github.com/tigera/canal/files/543392/canal.txt)
[canal.yaml.txt](https://github.com/tigera/canal/files/543396/canal.yaml.txt)

**Comment by caseydavenport** [comment]
@kharisj It looks like me like etcd is misconfigured. Can you share the way you're running etcd / double check that it is properly configured?

**Comment by galindro** [comment]
@caseydavenport 

   The same problem is occurring with me. According to this: https://github.com/projectcalico/canal/tree/master/k8s-install#etcd, I should first deploy an etcd cluster, which is already deployed by kubernetes and is accessible through localhost (127.0.0.1):

```bash
root@ip-10-0-1-100:~# docker ps |grep etcd
6bb535c6329f        gcr.io/google_containers/etcd-amd64:3.0.14-kubeadm              "etcd --listen-client"   About an hour ago   Up About an hour                        k8s_etcd.c323986f_etcd-ip-10-0-1-100_kube-system_3a26566bb004c61cd05382212e3f978f_c7322e1c
40cb3d87858f        gcr.io/google_containers/pause-amd64:3.0                        "/pause"                 About an hour ago   Up About an hour                        k8s_POD.d8dbe16c_etcd-ip-10-0-1-100_kube-system_3a26566bb004c61cd05382212e3f978f_e85d094a
```
```bash
root@ip-10-0-1-100:~# telnet localhost 2379
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
;quit


^C^CConnection closed by foreign host.
```
```bash
root@ip-10-0-1-100:~# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE
kube-system   calico-policy-controller-vg0qt          0/1       Error               3          58s
kube-system   canal-node-80ccl                        2/3       Error               3          58s
kube-system   canal-node-rhgsr                        3/3       Running             0          58s
kube-system   configure-canal-3zzfv                   0/1       Error               3          58s
kube-system   dummy-2088944543-vmn00                  1/1       Running             0          1h
kube-system   etcd-ip-10-0-1-100                      1/1       Running             0          1h
kube-system   kube-apiserver-ip-10-0-1-100            1/1       Running             0          1h
kube-system   kube-controller-manager-ip-10-0-1-100   1/1       Running             0          1h
kube-system   kube-discovery-1769846148-pvbpg         1/1       Running             0          1h
kube-system   kube-dns-2924299975-4mz8d               0/4       ContainerCreating   0          1h
kube-system   kube-proxy-bhp72                        1/1       Running             0          1h
kube-system   kube-proxy-lrwmp                        1/1       Running             0          1h
kube-system   kube-scheduler-ip-10-0-1-100            1/1       Running             0          1h
```
```bash
root@ip-10-0-1-100:~# kubectl describe -n kube-system po calico-policy-controller-vg0qt
Name:		calico-policy-controller-vg0qt
Namespace:	kube-system
Node:		ip-10-0-3-100/10.0.3.100
Start Time:	Tue, 10 Jan 2017 11:20:46 +0000
Labels:		k8s-app=calico-policy
Status:		Running
IP:		10.0.3.100
Controllers:	ReplicaSet/calico-policy-controller
Containers:
  calico-policy-controller:
    Container ID:	docker://3cbafaae49fd7713461b31997b615f3e93d8efabcf3ab15b476651a370fe4341
    Image:		calico/kube-policy-controller:v0.3.0
    Image ID:		docker-pullable://calico/kube-policy-controller@sha256:162b70b020a11f6eb51dca7b642ddb9fbfb9f22d34277ec901f1e541458bed59
    Port:		
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	255
      Started:		Tue, 10 Jan 2017 11:21:33 +0000
      Finished:		Tue, 10 Jan 2017 11:21:33 +0000
    Ready:		False
    Restart Count:	3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jtkqp (ro)
    Environment Variables:
      ETCD_ENDPOINTS:		<set to the key 'etcd_endpoints' of config map 'canal-config'>
      K8S_API:			https://kubernetes.default:443
      CONFIGURE_ETC_HOSTS:	true
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-jtkqp:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-jtkqp
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath					Type		Reason		Message
  ---------	--------	-----	----			-------------					--------	------		-------
  1m		1m		1	{default-scheduler }							Normal		Scheduled	Successfully assigned calico-policy-controller-vg0qt to ip-10-0-3-100
  1m		1m		1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal		Created		Created container with docker id f9200e773e13; Security:[seccomp=unconfined]
  1m		1m		1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal		Started		Started container with docker id f9200e773e13
  1m		1m		1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal		Started		Started container with docker id 532759b34b73
  1m		1m		1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal		Created		Created container with docker id 532759b34b73; Security:[seccomp=unconfined]
  1m		1m		2	{kubelet ip-10-0-3-100}							Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "calico-policy-controller" with CrashLoopBackOff: "Back-off 10s restarting failed container=calico-policy-controller pod=calico-policy-controller-vg0qt_kube-system(d4e636e6-d726-11e6-995e-02f485404c65)"

  1m	1m	1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal	Created		Created container with docker id c9c17ee27577; Security:[seccomp=unconfined]
  1m	1m	1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal	Started		Started container with docker id c9c17ee27577
  1m	47s	2	{kubelet ip-10-0-3-100}							Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "calico-policy-controller" with CrashLoopBackOff: "Back-off 20s restarting failed container=calico-policy-controller pod=calico-policy-controller-vg0qt_kube-system(d4e636e6-d726-11e6-995e-02f485404c65)"

  35s	35s	1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal	Started		Started container with docker id 3cbafaae49fd
  1m	35s	4	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal	Pulled		Container image "calico/kube-policy-controller:v0.3.0" already present on machine
  35s	35s	1	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Normal	Created		Created container with docker id 3cbafaae49fd; Security:[seccomp=unconfined]
  1m	9s	7	{kubelet ip-10-0-3-100}	spec.containers{calico-policy-controller}	Warning	BackOff		Back-off restarting failed docker container
  34s	9s	3	{kubelet ip-10-0-3-100}							Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "calico-policy-controller" with CrashLoopBackOff: "Back-off 40s restarting failed container=calico-policy-controller pod=calico-policy-controller-vg0qt_kube-system(d4e636e6-d726-11e6-995e-02f485404c65)"
```

```bash
root@ip-10-0-1-100:~# kubectl logs calico-policy-controller-vg0qt -c calico-policy-controller -n kube-system
2017-01-10 11:21:07,867 7 INFO Configuring /etc/hosts
2017-01-10 11:21:07,867 7 INFO Appended 'kubernetes.default  -> 10.96.0.1' to /etc/hosts
2017-01-10 11:21:07,868 7 INFO Beginning execution
2017-01-10 11:21:07,868 7 INFO Leader election enabled? False
Traceback (most recent call last):
  File "<string>", line 502, in <module>
  File "<string>", line 138, in run
  File "site-packages/pycalico/datastore.py", line 828, in set_policy_tier_metadata
  File "site-packages/etcd/client.py", line 461, in write
  File "site-packages/etcd/client.py", line 834, in wrapper
etcd.EtcdConnectionFailed: Connection to etcd failed due to MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=2379): Max retries exceeded with url: /v2/keys/calico/v1/policy/tier/k8s-network-policy/metadata (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe776981290>: Failed to establish a new connection: [Errno 111] Connection refused',))",)
```

```bash
root@ip-10-0-1-100:~# kubectl logs configure-canal-3zzfv -c configure-flannel -n kube-system
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused

root@ip-10-0-1-100:~# kubectl describe -n kube-system po configure-canal-3zzfv
Name:		configure-canal-3zzfv
Namespace:	kube-system
Node:		ip-10-0-3-100/10.0.3.100
Start Time:	Tue, 10 Jan 2017 11:20:46 +0000
Labels:		controller-uid=d4de65e3-d726-11e6-995e-02f485404c65
		job-name=configure-canal
Status:		Running
IP:		10.0.3.100
Controllers:	Job/configure-canal
Containers:
  configure-flannel:
    Container ID:	docker://a61a22bcc7b5ef5f6574338d8935fa7d9d6678464b31bc57c55810fc739d8658
    Image:		quay.io/coreos/etcd:v3.0.9
    Image ID:		docker-pullable://quay.io/coreos/etcd@sha256:fc6d3d51a069614737131e78ab03fc36e8c1ed2d264fbb6a23a4e946aa106a45
    Port:		
    Command:
      etcdctl
      set
      /coreos.com/network/config
      { "Network": "192.168.0.0/16", "Backend": {"Type": "vxlan"} }
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	2
      Started:		Tue, 10 Jan 2017 11:23:52 +0000
      Finished:		Tue, 10 Jan 2017 11:23:52 +0000
    Ready:		False
    Restart Count:	5
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jtkqp (ro)
    Environment Variables:
      ETCDCTL_PEERS:	<set to the key 'etcd_endpoints' of config map 'canal-config'>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-jtkqp:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-jtkqp
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath				Type		Reason		Message
  ---------	--------	-----	----			-------------				--------	------		-------
  3m		3m		1	{default-scheduler }						Normal		Scheduled	Successfully assigned configure-canal-3zzfv to ip-10-0-3-100
  3m		3m		1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal		Created		Created container with docker id 742f65799c81; Security:[seccomp=unconfined]
  3m		3m		1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal		Started		Started container with docker id 742f65799c81
  3m		3m		1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal		Created		Created container with docker id 374fa6c5ee3a; Security:[seccomp=unconfined]
  3m		3m		1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal		Started		Started container with docker id 374fa6c5ee3a
  3m		3m		2	{kubelet ip-10-0-3-100}						Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "configure-flannel" with CrashLoopBackOff: "Back-off 10s restarting failed container=configure-flannel pod=configure-canal-3zzfv_kube-system(d4e06be9-d726-11e6-995e-02f485404c65)"

  3m	3m	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Created		Created container with docker id 1c97952d6693; Security:[seccomp=unconfined]
  3m	3m	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Started		Started container with docker id 1c97952d6693
  3m	3m	2	{kubelet ip-10-0-3-100}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "configure-flannel" with CrashLoopBackOff: "Back-off 20s restarting failed container=configure-flannel pod=configure-canal-3zzfv_kube-system(d4e06be9-d726-11e6-995e-02f485404c65)"

  2m	2m	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Created		Created container with docker id b7c5d525176d; Security:[seccomp=unconfined]
  2m	2m	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Started		Started container with docker id b7c5d525176d
  2m	2m	4	{kubelet ip-10-0-3-100}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "configure-flannel" with CrashLoopBackOff: "Back-off 40s restarting failed container=configure-flannel pod=configure-canal-3zzfv_kube-system(d4e06be9-d726-11e6-995e-02f485404c65)"

  1m	1m	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Started		Started container with docker id 1abfeec0c9aa
  1m	1m	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Created		Created container with docker id 1abfeec0c9aa; Security:[seccomp=unconfined]
  1m	37s	7	{kubelet ip-10-0-3-100}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "configure-flannel" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=configure-flannel pod=configure-canal-3zzfv_kube-system(d4e06be9-d726-11e6-995e-02f485404c65)"

  3m	26s	6	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Pulled		Container image "quay.io/coreos/etcd:v3.0.9" already present on machine
  26s	26s	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Created		Created container with docker id a61a22bcc7b5; Security:[seccomp=unconfined]
  26s	26s	1	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Normal	Started		Started container with docker id a61a22bcc7b5
  3m	12s	17	{kubelet ip-10-0-3-100}	spec.containers{configure-flannel}	Warning	BackOff		Back-off restarting failed docker container
  25s	12s	2	{kubelet ip-10-0-3-100}						Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "configure-flannel" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=configure-flannel pod=configure-canal-3zzfv_kube-system(d4e06be9-d726-11e6-995e-02f485404c65)"

```

```bash
root@ip-10-0-1-100:~# kubectl logs configure-canal-3zzfv -c configure-flannel -n kube-system
Error:  client: etcd cluster is unavailable or misconfigured
error #0: dial tcp 127.0.0.1:2379: getsockopt: connection refused
```
